// Generated by gencpp from file thorvald_sprayer/CANopen_srv.msg
// DO NOT EDIT!


#ifndef THORVALD_SPRAYER_MESSAGE_CANOPEN_SRV_H
#define THORVALD_SPRAYER_MESSAGE_CANOPEN_SRV_H

#include <ros/service_traits.h>


#include <thorvald_sprayer/CANopen_srvRequest.h>
#include <thorvald_sprayer/CANopen_srvResponse.h>


namespace thorvald_sprayer
{

struct CANopen_srv
{

typedef CANopen_srvRequest Request;
typedef CANopen_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CANopen_srv
} // namespace thorvald_sprayer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thorvald_sprayer::CANopen_srv > {
  static const char* value()
  {
    return "f8d20e0fc83f153976971528075db05b";
  }

  static const char* value(const ::thorvald_sprayer::CANopen_srv&) { return value(); }
};

template<>
struct DataType< ::thorvald_sprayer::CANopen_srv > {
  static const char* value()
  {
    return "thorvald_sprayer/CANopen_srv";
  }

  static const char* value(const ::thorvald_sprayer::CANopen_srv&) { return value(); }
};


// service_traits::MD5Sum< ::thorvald_sprayer::CANopen_srvRequest> should match 
// service_traits::MD5Sum< ::thorvald_sprayer::CANopen_srv > 
template<>
struct MD5Sum< ::thorvald_sprayer::CANopen_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_sprayer::CANopen_srv >::value();
  }
  static const char* value(const ::thorvald_sprayer::CANopen_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_sprayer::CANopen_srvRequest> should match 
// service_traits::DataType< ::thorvald_sprayer::CANopen_srv > 
template<>
struct DataType< ::thorvald_sprayer::CANopen_srvRequest>
{
  static const char* value()
  {
    return DataType< ::thorvald_sprayer::CANopen_srv >::value();
  }
  static const char* value(const ::thorvald_sprayer::CANopen_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thorvald_sprayer::CANopen_srvResponse> should match 
// service_traits::MD5Sum< ::thorvald_sprayer::CANopen_srv > 
template<>
struct MD5Sum< ::thorvald_sprayer::CANopen_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thorvald_sprayer::CANopen_srv >::value();
  }
  static const char* value(const ::thorvald_sprayer::CANopen_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thorvald_sprayer::CANopen_srvResponse> should match 
// service_traits::DataType< ::thorvald_sprayer::CANopen_srv > 
template<>
struct DataType< ::thorvald_sprayer::CANopen_srvResponse>
{
  static const char* value()
  {
    return DataType< ::thorvald_sprayer::CANopen_srv >::value();
  }
  static const char* value(const ::thorvald_sprayer::CANopen_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THORVALD_SPRAYER_MESSAGE_CANOPEN_SRV_H
