// Generated by gencpp from file thorvald_sprayer/CANopen_srvRequest.msg
// DO NOT EDIT!


#ifndef THORVALD_SPRAYER_MESSAGE_CANOPEN_SRVREQUEST_H
#define THORVALD_SPRAYER_MESSAGE_CANOPEN_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thorvald_sprayer
{
template <class ContainerAllocator>
struct CANopen_srvRequest_
{
  typedef CANopen_srvRequest_<ContainerAllocator> Type;

  CANopen_srvRequest_()
    : can_id(0)
    , length(0)
    , data()  {
      data.assign(0);
  }
  CANopen_srvRequest_(const ContainerAllocator& _alloc)
    : can_id(0)
    , length(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef int32_t _can_id_type;
  _can_id_type can_id;

   typedef int32_t _length_type;
  _length_type length;

   typedef boost::array<uint16_t, 2>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CANopen_srvRequest_

typedef ::thorvald_sprayer::CANopen_srvRequest_<std::allocator<void> > CANopen_srvRequest;

typedef boost::shared_ptr< ::thorvald_sprayer::CANopen_srvRequest > CANopen_srvRequestPtr;
typedef boost::shared_ptr< ::thorvald_sprayer::CANopen_srvRequest const> CANopen_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thorvald_sprayer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'thorvald_sprayer': ['/home/thomasdegallaix-ubuntu/catkin_ws/src/thorvald_sprayer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77dd4ca2d5cfa5d7d609b38bd8fbad45";
  }

  static const char* value(const ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77dd4ca2d5cfa5d7ULL;
  static const uint64_t static_value2 = 0xd609b38bd8fbad45ULL;
};

template<class ContainerAllocator>
struct DataType< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thorvald_sprayer/CANopen_srvRequest";
  }

  static const char* value(const ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 can_id\n\
int32 length\n\
uint16[2] data\n\
";
  }

  static const char* value(const ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.can_id);
      stream.next(m.length);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANopen_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thorvald_sprayer::CANopen_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "can_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.can_id);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THORVALD_SPRAYER_MESSAGE_CANOPEN_SRVREQUEST_H
