// Generated by gencpp from file thorvald_sprayer/feedbackData.msg
// DO NOT EDIT!


#ifndef THORVALD_SPRAYER_MESSAGE_FEEDBACKDATA_H
#define THORVALD_SPRAYER_MESSAGE_FEEDBACKDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thorvald_sprayer
{
template <class ContainerAllocator>
struct feedbackData_
{
  typedef feedbackData_<ContainerAllocator> Type;

  feedbackData_()
    : pressure(0)  {
    }
  feedbackData_(const ContainerAllocator& _alloc)
    : pressure(0)  {
  (void)_alloc;
    }



   typedef uint32_t _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::thorvald_sprayer::feedbackData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thorvald_sprayer::feedbackData_<ContainerAllocator> const> ConstPtr;

}; // struct feedbackData_

typedef ::thorvald_sprayer::feedbackData_<std::allocator<void> > feedbackData;

typedef boost::shared_ptr< ::thorvald_sprayer::feedbackData > feedbackDataPtr;
typedef boost::shared_ptr< ::thorvald_sprayer::feedbackData const> feedbackDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thorvald_sprayer::feedbackData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thorvald_sprayer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'thorvald_sprayer': ['/home/thomasdegallaix-ubuntu/catkin_ws/src/thorvald_sprayer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::feedbackData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::feedbackData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::feedbackData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1169f7bffca25caef495c23afe53b2b8";
  }

  static const char* value(const ::thorvald_sprayer::feedbackData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1169f7bffca25caeULL;
  static const uint64_t static_value2 = 0xf495c23afe53b2b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thorvald_sprayer/feedbackData";
  }

  static const char* value(const ::thorvald_sprayer::feedbackData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 pressure\n\
";
  }

  static const char* value(const ::thorvald_sprayer::feedbackData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feedbackData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thorvald_sprayer::feedbackData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thorvald_sprayer::feedbackData_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THORVALD_SPRAYER_MESSAGE_FEEDBACKDATA_H
