// Generated by gencpp from file thorvald_sprayer/sprayer_controllerResponse.msg
// DO NOT EDIT!


#ifndef THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERRESPONSE_H
#define THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thorvald_sprayer
{
template <class ContainerAllocator>
struct sprayer_controllerResponse_
{
  typedef sprayer_controllerResponse_<ContainerAllocator> Type;

  sprayer_controllerResponse_()
    : message()  {
    }
  sprayer_controllerResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sprayer_controllerResponse_

typedef ::thorvald_sprayer::sprayer_controllerResponse_<std::allocator<void> > sprayer_controllerResponse;

typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerResponse > sprayer_controllerResponsePtr;
typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerResponse const> sprayer_controllerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thorvald_sprayer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'thorvald_sprayer': ['/home/thomasdegallaix-ubuntu/catkin_ws/src/thorvald_sprayer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thorvald_sprayer/sprayer_controllerResponse";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
\n\
\n\
";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sprayer_controllerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thorvald_sprayer::sprayer_controllerResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERRESPONSE_H
