// Generated by gencpp from file thorvald_sprayer/sprayer_controllerRequest.msg
// DO NOT EDIT!


#ifndef THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERREQUEST_H
#define THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace thorvald_sprayer
{
template <class ContainerAllocator>
struct sprayer_controllerRequest_
{
  typedef sprayer_controllerRequest_<ContainerAllocator> Type;

  sprayer_controllerRequest_()
    : order()
    , nodeID(0)  {
    }
  sprayer_controllerRequest_(const ContainerAllocator& _alloc)
    : order(_alloc)
    , nodeID(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_type;
  _order_type order;

   typedef uint32_t _nodeID_type;
  _nodeID_type nodeID;





  typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sprayer_controllerRequest_

typedef ::thorvald_sprayer::sprayer_controllerRequest_<std::allocator<void> > sprayer_controllerRequest;

typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerRequest > sprayer_controllerRequestPtr;
typedef boost::shared_ptr< ::thorvald_sprayer::sprayer_controllerRequest const> sprayer_controllerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace thorvald_sprayer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'thorvald_sprayer': ['/home/thomasdegallaix-ubuntu/catkin_ws/src/thorvald_sprayer/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676304f02b97209d9bf7d76781b19ce3";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676304f02b97209dULL;
  static const uint64_t static_value2 = 0x9bf7d76781b19ce3ULL;
};

template<class ContainerAllocator>
struct DataType< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "thorvald_sprayer/sprayer_controllerRequest";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string order\n\
uint32 nodeID\n\
";
  }

  static const char* value(const ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
      stream.next(m.nodeID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sprayer_controllerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::thorvald_sprayer::sprayer_controllerRequest_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order);
    s << indent << "nodeID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.nodeID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THORVALD_SPRAYER_MESSAGE_SPRAYER_CONTROLLERREQUEST_H
